trigger:
  branches:
    include:
      - master
      - dev

stages:
- stage:
  displayName: 'Docker Configuration'
  jobs:
    - job:
      steps:
        - script: docker login -u souzamateus99 -p matcar123
- stage: Build
  jobs:
  - job:
    displayName: 'Build and Push Docker an image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub - souzamateus99'
        repository: 'medical-appointment-api'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'