trigger:
- dev
- master

stages:
- stage: MavenBuild
  displayName: 'Maven Build'
  jobs:
    - job:
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'

- stage:
  displayName: 'Docker build and Push'
  dependsOn: 'MavenBuild'
  condition: in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/dev')
  jobs:
  - job:
    displayName: 'Build and Push Docker an image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub - souzamateus99'
        repository: 'souzamateus99/medical-appointment-api'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
