trigger:
- dev
- master

stages:
- stage: Configuration
  displayName: Config stage
  jobs:
    - job:
      displayName: 'Replace tokens in AppConfig.json'
      steps:
        - task: replacetokens@3
          inputs:
            rootDirectory: '$(System.DefaultWorkingDirectory)/_ZeDouto.zedouto.api.medicalappointments/drop/src/main/resources'
            targetFiles: 'AppConfig.json'
            encoding: 'auto'
            writeBOM: true
            actionOnMissing: 'warn'
            keepToken: false
            tokenPrefix: '#{'
            tokenSuffix: '}#'
            useLegacyPattern: false
            enableTelemetry: true

- stage: Build
  jobs:
  - job:
    displayName: 'Build and Push Docker an image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub - souzamateus99'
        repository: 'souzamateus99/medical-appointment-api'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
