trigger:
- dev
- master

stages:
- stage: Build
  jobs:
  - job:
    displayName: 'Build and Push Docker an image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub - souzamateus99'
        repository: 'souzamateus99/medical-appointment-api'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
