trigger:
  branches:
    include:
      - master
      - dev

stages:
- stage: Build
  jobs:
  - job:
    displayName: 'Build Docker image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub - souzamateus99'
        repository: 'medical-appointment-api'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'